# Cloud Build configuration
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/aktivio-development/aktivio-flask:$COMMIT_SHA', '.']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'aktivio-flask',
        '--image',
        'gcr.io/aktivio-development/aktivio-flask:$COMMIT_SHA',
        '--region',
        '$_REGION',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

# Substitutions for Cloud Build
substitutions:
  _REGION: asia-southeast2